### ISSUE TITLE
FIx Install section in README.md

### ISSUE THREAD

**Issue by kqnade** [Q0tzly/ymd#2]
I installed and ran this script, but it won't download.
It is because download path is not set correctly.
You should fix it to add the download path sub section to the install section of the readme.md.

```diff
- d_path = '/Users/yuto/Downloads'
+ d_path = '$HOME/Downloads'
```
or
Make new function to set download path.

Thank you 0w0/

**Comment by Q0tzly** [comment]
Fixed it.
Thank for telling me it .
